
[common]
connstr = "http://localhost:8545"
keydir = "/Users/yekai/eth/data/keystore"
ContractAddr = "0x"
Buildpath  =  "build2"
Codepath  =  "callsol.go"
TestCodepath  =  "testFunc.go"
TestConfigpath  =  "config.toml"

[Deploy]
func =  "DeployPdbank"
fromaddr  =  "0x70c53a4c94ccce9ce56effbfcb89b221f986cd41"
pass  = "123"
Params =  "DeployPdbank(auth,testclient,"pdj")"
TestAddr = ""
TestPass = ""

[[NoGasFuncConfs]]
func =  "TotalAmount"
Constructor = "NewPdbank"
funcparams  =  "TotalAmount(nil)"
retparams  =  "data0,err"

[[NoGasFuncConfs]]
func =  "BankName"
Constructor = "NewPdbank"
funcparams  =  "BankName(nil)"
retparams  =  "data0,err"

[[NoGasFuncConfs]]
func =  "Balances"
Constructor = "NewPdbank"
funcparams  =  "Balances(nil,common.HexToAddress(Config.Deploy.TestAddr))"
retparams  =  "data0,err"

[[funcConfs]]
func =  "Withdraw"
Constructor = "NewPdbank"
value  = 0
funcparams  =  "Withdraw(auth)"

[[NoGasFuncConfs]]
func =  "Owner"
Constructor = "NewPdbank"
funcparams  =  "Owner(nil)"
retparams  =  "data0,err"

[[funcConfs]]
func =  "Deposit"
Constructor = "NewPdbank"
value  = 0
funcparams  =  "Deposit(auth)"

[[funcConfs]]
func =  ""
Constructor = "NewPdbank"
value  = 0
funcparams  =  "(auth,"testXXX")"
