[common]
connstr = "http://localhost:8545"  #以太坊地址
keydir = "/Users/yekai/eth/data/keystore"  #私钥所在目录
contractaddr = "0xe98a031548fc8e8580e1d2d67637045a82b5250c" #合约地址，部署后拿到
buildpath = "build" #合约地址，部署后拿到
Codepath  =  "callsol.go"  #生成目标代码路径
TestCodepath  =  "testFunc.go" #生成调用时的目标代码路径
TestConfigpath  =  "config.toml" #生成调用时的目标代码路径


[Deploy]
contractname =  "Pdbank"  #部署合约函数，合约编译成go语言后，可以得到
fromaddr  =  "0x70c53a4c94ccce9ce56effbfcb89b221f986cd41" #部署用的账户地址，需要消耗gas
pass  = "123"  #账户地址对应的密码
AbiFile =  "contracts/pdbank.abi"  #编译后ABI文件所在路径